# Generated by Django 4.2.7 on 2024-05-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
