# Generated by Django 4.2.7 on 2024-05-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_scheduledlecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
